#cloud-config

# See:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html
autoinstall:
  # Stop the annoying network timeout on boot:
  # Job systemd-networkd-wait-online.service/start running (50s / no limit)
  network:
    version: 2
    ethernets:
      id0:
        match:
          name: en*
        dhcp4: true
        optional: true
      id1:
        match:
          name: eth*
        dhcp4: true
        optional: true

  # All cloud-init configurations must have an identity.
  identity:
    hostname: LH6224
    username: jnesta
    password: $6$QpZkxesFczJrJtX4$6CtBBHmzC4LA8VAPYtKFoM88QkJN9Th8tCUYu9R.I6sFt21/wXP1/.JPKI26t0QIrLUr.65Ixod2WMf.rxa/K0 # cspell:disable-line

  # By default, standard Ubuntu Server will be installed. We could install minimal instead, but this
  # leads to installation crashes on Dell laptops, so we keep the default.
  # https://askubuntu.com/questions/1276664/how-can-i-make-a-minimal-installation-with-autoinstall

  # This section runs commands after installation but before the first reboot.
  late-commands:
    # On the first boot, after about 30 seconds, output from "cloud init" shows up in the terminal
    # relating to SSH keys.
    - touch /target/etc/cloud/cloud-init.disabled

    # The installation USB drive is mounted at: /cdrom
    # The new root filesystem is at: /target
    - mkdir --parents /target/home/jnesta/auto-install
    - cp --recursive /cdrom/post-install /target/home/jnesta
    - chown --recursive jnesta:jnesta /target/home/jnesta

  version: 1
