#cloud-config

# By default, standard Ubuntu Server will be installed. We could install minimal instead, but this
# leads to installation crashes on Dell laptops, so we keep the default.
# https://askubuntu.com/questions/1276664/how-can-i-make-a-minimal-installation-with-autoinstall

# See:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html
autoinstall:
  # All cloud-init configurations must have an identity.
  identity:
    hostname: LH6224
    username: jnesta
    # cspell:disable-next-line
    password: $y$j9T$wD6g6uau8MzskrXlLYZ5A.$XeD3Wim4mOvC8JgFpKsivT5KlekvkscXAJaF1YzIkvC

  # This section runs commands after installation but before the first reboot.
  late-commands:
    # The installation USB drive is mounted at: /cdrom
    # The new root filesystem is at: /target
    - mkdir /target/home/jnesta
    - cp --recursive /cdrom/post-install /target/home/jnesta

    # Since the installer is running as root, the user's directory will be owned by root, so we have
    # to manually fix it. We have to use the numeric UID since the user does not exist on the
    # installer. (The first account on the system will always have a UID of 1000 and the first group
    # on the system will always have a GID of 1000.)
    - chown --recursive 1000:1000 /target/home/jnesta

    # Set automatic login on boot.
    - sudo mkdir --parents /target/etc/systemd/system/getty@tty1.service.d
    - cp /cdrom/post-install/etc/systemd/override.conf /target/etc/systemd/system/getty@tty1.service.d/override.conf

  # Stop the annoying network timeout on boot:
  # Job systemd-networkd-wait-online.service/start running (50s / no limit)
  network:
    version: 2
    ethernets:
      id0:
        match:
          name: en*
        dhcp4: true
        optional: true
      id1:
        match:
          name: eth*
        dhcp4: true
        optional: true

  # Encrypt the disk.
  storage:
    layout:
      name: lvm
      password: hunter2

  # This section is passed to the installed system's cloud-init and the commands run on the first
  # boot.
  user-data:
    runcmd:
      # By default, SSH host keys and other information is printed to the console around 30 settings
      # after the first boot, which is confusing/distracting. Since cloud-init has already created
      # our user, we do not need it to be enabled anymore.
      - touch /etc/cloud/cloud-init.disabled

      # Set the post-installation script to automatically run once the user logs in for the first
      # time.
      - echo '# --- TEMP ---' >> /home/jnesta/.profile
      - echo '"$HOME/post-install/post-install.sh"' >> /home/jnesta/.profile
      - echo '# --- TEMP ---' >> /home/jnesta/.profile
      - chown 1000:1000 /home/jnesta/.profile

      # Write the BitWarden master password to disk so that the post-installation script can use it.
      # (This will be deleted later by the post-installation script.)
      - echo 'hunter2' >> /home/jnesta/bitwarden_password
      - chown 1000:1000 /home/jnesta/bitwarden_password

    # Make it so that the user does not require a password to use sudo so that the post-installation
    # script can be completely automated. (This will be changed back to the default at the end of
    # the post-installation script.)
    users:
      - name: jnesta
        sudo: "ALL=(ALL) NOPASSWD: ALL"

  version: 1
