#cloud-config

# By default, standard Ubuntu Server will be installed. We could install minimal instead, but this
# leads to installation crashes on Dell laptops, so we keep the default.
# https://askubuntu.com/questions/1276664/how-can-i-make-a-minimal-installation-with-autoinstall

# See:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html
autoinstall:
  # All cloud-init configurations must have an identity.
  identity:
    hostname: LH6224
    username: jnesta
    # cspell:disable-next-line
    password: $y$j9T$wD6g6uau8MzskrXlLYZ5A.$XeD3Wim4mOvC8JgFpKsivT5KlekvkscXAJaF1YzIkvC

  # This section runs commands after installation but before the first boot.
  # - The installation USB drive is mounted at: /cdrom
  # - The new root filesystem is at: /target
  late-commands:
    # Set automatic login.
    - sudo mkdir -p /target/etc/systemd/system/getty@tty1.service.d
    - cp /cdrom/post-install/etc/systemd/override.conf /target/etc/systemd/system/getty@tty1.service.d/

    # Copy the post-installation script and related files to the system.
    - cp --recursive /cdrom/post-install /target/post-install
    - chmod +x /target/post-install/post-install.sh

    # Set the post-installation script to automatically run once the user logs in for the first
    # time. Note that:
    # - When the operating system creates a user, it will also create a stock ".profile" file that
    #   includes things like loading the ".bashrc" file. Creating the file before the user exists
    #   will prevent that from occurring, so we explicitly include all of the stock lines in the
    #   copied ".profile" file.
    # - The "user-data" --> "run_cmd" section can be used to run commands on the first boot, but we
    #   cannot use it for this purpose because the automatic login occurs first. In other words, any
    #   modifications to "/home/jnesta/.profile" would not take effect.
    - mkdir -p /target/home/jnesta
    - cp /cdrom/post-install/.profile /target/home/jnesta/

    # Copy the SSH public and private key.
    - mkdir /target/home/jnesta/.ssh
    - cp /cdrom/post-install/.ssh/id_ed25519 /target/home/jnesta/.ssh/id_ed25519
    - chmod 600 /target/home/jnesta/.ssh/id_ed25519
    - cp /cdrom/post-install/.ssh/id_ed25519.pub /target/home/jnesta/.ssh/id_ed25519.pub

    # Since the installer is running as root, the user's directory will be owned by root, so we have
    # to manually fix it. We have to use the numeric UID since the user does not exist on the
    # installer. (The first account on the system will always have a UID of 1000 and the first group
    # on the system will always have a GID of 1000.)
    - chown --recursive 1000:1000 /target/home/jnesta

    # By default, SSH host keys and other information is printed to the console around 30 settings
    # after the first boot, which is confusing/distracting. (Even with these changes, "cloud-init"
    # will still display some output to the console.)
    - sed --in-place "s/- ssh_authkey_fingerprints/#- ssh_authkey_fingerprints/g" /target/etc/cloud/cloud.cfg
    - sed --in-place "s/- keys_to_console/#- keys_to_console/g" /target/etc/cloud/cloud.cfg
    - sed --in-place "s/- final_message/#- final_message/g" /target/etc/cloud/cloud.cfg

  # Stop the annoying network timeout on boot:
  # Job systemd-networkd-wait-online.service/start running (50s / no limit)
  network:
    version: 2
    ethernets:
      id0:
        match:
          name: en*
        dhcp4: true
        optional: true
      id1:
        match:
          name: eth*
        dhcp4: true
        optional: true

  # Encrypt the disk.
  storage:
    layout:
      name: lvm
      password: "hunter2"

  # This section is passed to the installed system's cloud-init.
  user-data:
    # Make it so that the user does not require a password to use sudo so that the post-installation
    # script can be completely automated. (This will be changed back to the default at the end of
    # the post-installation script.)
    users:
      - name: jnesta
        sudo: "ALL=(ALL) NOPASSWD: ALL"

  version: 1
