#cloud-config

# By default, standard Ubuntu Server will be installed. We could install minimal instead, but this
# leads to installation crashes on Dell laptops, so we keep the default.
# https://askubuntu.com/questions/1276664/how-can-i-make-a-minimal-installation-with-autoinstall

# See:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html
autoinstall:
  # All cloud-init configurations must have an identity.
  identity:
    hostname: LH6224
    username: jnesta
    # cspell:disable-next-line
    password: $y$j9T$wD6g6uau8MzskrXlLYZ5A.$XeD3Wim4mOvC8JgFpKsivT5KlekvkscXAJaF1YzIkvC

  # This section runs commands after installation but before the first reboot.
  late-commands:
    # By default, SSH host keys and other information is printed to the console around 30 settings
    # after the first boot, which is confusing/distracting. (Even with these changes, "cloud-init"
    # will still display some output to the console, but it is impossible to stop entirely.)
    - sed --in-place 's/- ssh_authkey_fingerprints/#- ssh_authkey_fingerprints/g' /target/etc/cloud/cloud.cfg
    - sed --in-place 's/- keys_to_console/#- keys_to_console/g' /target/etc/cloud/cloud.cfg
    - sed --in-place 's/- final_message/#- final_message/g' /target/etc/cloud/cloud.cfg

    # The installation USB drive is mounted at: /cdrom
    # The new root filesystem is at: /target
    - mkdir /target/home/jnesta
    - cp --recursive /cdrom/post-install /target/home/jnesta
    # The "jnesta" directory will now be owned by the root user, so we have to manually fix it.
    # We have to use the numeric UID since the "jnesta" user does not exist on the installer. (The
    # first account on the system will always have a UID of 1000 and the first group on the system
    # will always have a UID of 1000.)
    - chown --recursive 1000:1000 /target/home/jnesta

  # Stop the annoying network timeout on boot:
  # Job systemd-networkd-wait-online.service/start running (50s / no limit)
  network:
    version: 2
    ethernets:
      id0:
        match:
          name: en*
        dhcp4: true
        optional: true
      id1:
        match:
          name: eth*
        dhcp4: true
        optional: true

  version: 1
