#cloud-config

# 1) Use Rufus to create a USB drive from an Ubuntu Server installation ISO.
# 2) Place this file in the root of the USB drive.
# 3) Place the "post-install" directory in the root of the USB drive.
# 4) Edit the "/boot/grub/grub.cfg" file:
#
#    set timeout=30
#    -->
#    set timeout=1
#
#    linux	/casper/vmlinuz  ---
#    -->
#    linux	/casper/vmlinuz autoinstall cloud-init=disabled ---
#
#    Explanation:
#    - autoinstall
#      - Needed to load the "autoinstall.yaml" file.
#      - This file can also be called "user-data" instead of "autoinstall.yaml", which is required
#        if using cloud-init.
#      - We do not have to specify "s=", because it will look for "autoinstall.yaml" at the root by
#        default.
#      - Adding this is potentially dangerous because now the installer will automatically blow away
#        the hard drive.
#    - cloud-init=disabled
#      - cloud-init is enabled by default and will wait for a long time waiting for the Ethernet
#        device to come up. Since on a laptop we do not typically have the Ethernet cable plugged
#        in, we can disable it to prevent the long period of lag.

# See:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/howto/autoinstall-quickstart.html
autoinstall:
  # Stop the annoying network timeout on boot:
  # Job systemd-networkd-wait-online.service/start running (50s / no limit)
  network:
    version: 2
    ethernets:
      id0:
        match:
          name: en*
        dhcp4: true
        optional: true
      id1:
        match:
          name: eth*
        dhcp4: true
        optional: true

  # All cloud-init configurations must have an identity.
  identity:
    hostname: LH6224
    username: jnesta
    password: $6$QpZkxesFczJrJtX4$6CtBBHmzC4LA8VAPYtKFoM88QkJN9Th8tCUYu9R.I6sFt21/wXP1/.JPKI26t0QIrLUr.65Ixod2WMf.rxa/K0 # cspell:disable-line

  # By default, standard Ubuntu Server will be installed. We could install minimal instead, but this
  # leads to installation crashes on Dell laptops, so we keep the default.
  # https://askubuntu.com/questions/1276664/how-can-i-make-a-minimal-installation-with-autoinstall

  # This section runs commands after installation but before the first reboot.
  late-commands:
    # On the first boot, after about 30 seconds, output from "cloud init" shows up in the terminal
    # relating to SSH keys.
    - touch /target/etc/cloud/cloud-init.disabled

    # The installation USB drive is mounted at: /cdrom
    # The new root filesystem is at: /target
    - mkdir --parents /target/home/jnesta/auto-install
    - cp --recursive /cdrom/post-install /target/home/jnesta
    - chown --recursive jnesta:jnesta /target/home/jnesta

  version: 1
